/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package spdx

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestDetectSBOMEncoding(t *testing.T) {
	for _, tc := range []struct {
		fragment         string
		shouldErr        bool
		expectedEncoding string
	}{
		{
			`SPDXVersion: SPDX-2.2
    DataLicense: CC0-1.0
    SPDXID: SPDXRef-DOCUMENT
    DocumentName: Tern report for nginx
    DocumentNamespace: https://spdx.org/spdxdocs/tern-report-2.10.1-nginx-5fc8720c-a097-4825-afd2-17fe2c32981c
    LicenseListVersion: 3.8
    Creator: Tool: tern-2.10.1
    Created: 2022-07-04T18:43:35Z
    DocumentComment: <text>This document was generated by the Tern Project: https://github.com/tern-tools/tern</text>

    PackageName: nginx
    SPDXID: SPDXRef-nginx-latest
    PackageVersion: latest
    PackageDownloadLocation: NOASSERTION
    FilesAnalyzed: false
    PackageLicenseConcluded: NOASSERTION
    PackageLicenseDeclared: NOASSERTION
    PackageCopyrightText: NOASSERTION
`,
			false,
			"spdx",
		},
		{
			`{
    "SPDXID": "SPDXRef-DOCUMENT",
    "name": "sbom-sha256:3b72bb7f7ce12357a17d40f5198708823333790dd20d460613a9cdaabc97bdd6",
    "spdxVersion": "SPDX-2.2",
    "creationInfo": {
      "created": "2022-07-01T02:27:39Z",
      "creators": [
        "Tool: ko (devel)"
      ]
    },
    "dataLicense": "CC0-1.0",
    "documentNamespace": "http://spdx.org/spdxdocs/kosha256:3b72bb7f7ce12357a17d40f5198708823333790dd20d460613a9cdaabc97bdd6",
    "documentDescribes": [
      "SPDXRef-Package-sha256-3b72bb7f7ce12357a17d40f5198708823333790dd20d460613a9cdaabc97bdd6"
    ],
    "packages": [
  `,
			false,
			"spdx+json",
		},
		{
			// Junk in file
			`lskjdflksjdflkjsdf`,
			false,
			"",
		},
	} {
		tmp, err := os.CreateTemp("", "")
		require.NoError(t, err)
		defer os.Remove(t.Name())
		require.NoError(t, os.WriteFile(tmp.Name(), []byte(tc.fragment), os.FileMode(0o0644)))
		format, err := DetectSBOMEncoding(tmp)
		if tc.shouldErr {
			require.Error(t, err)
		} else {
			require.Equal(t, tc.expectedEncoding, format)
		}
	}
}

// TestOpenDocNonConformant opens real-world documents that violate
// the SPDX specification. protobom, which documents are now parsed
// with, validates them against the schema and rejects both, where the
// previous hand-rolled parser read the fields it recognized: one omits
// spdxVersion and the SPDXRef- prefix of its identifiers, the other
// carries package originators that are neither NOASSERTION nor a
// "Person:"/"Organization:" value. The reader retries such documents
// with those violations repaired, so they still open.
func TestOpenDocNonConformant(t *testing.T) {
	for _, tc := range []struct {
		path     string
		packages int
	}{
		{path: "testdata/images.spdx.json", packages: 1},
		{path: "testdata/external-references.spdx.json", packages: 1},
	} {
		t.Run(tc.path, func(t *testing.T) {
			doc, err := OpenDoc(tc.path)
			require.NoError(t, err)
			require.Len(t, doc.Packages, tc.packages)
		})
	}
}

// TestOpenDocLegacyRendering reads documents rendered by the legacy
// template renderer, which lists the files of a package right after
// it: the files must come back related to their package, in both SPDX
// versions bom has published (Kubernetes release SBOMs declared 2.2 up
// to 1.23).
func TestOpenDocLegacyRendering(t *testing.T) {
	for _, version := range []string{"SPDX-2.2", "SPDX-2.3"} {
		t.Run(version, func(t *testing.T) {
			ldoc := NewDocument()
			ldoc.Version = version
			ldoc.Name = "legacy-doc"
			ldoc.Namespace = "https://sbom.k8s.io/test/legacy"

			pkg := NewPackage()
			pkg.SetSPDXID("SPDXRef-Package-kubectl")
			pkg.Name = "kubectl"
			pkg.Version = "v1.33.0"
			pkg.LicenseConcluded = "Apache-2.0"
			require.NoError(t, ldoc.AddPackage(pkg))

			file := NewFile()
			file.SetSPDXID("SPDXRef-File-kubectl-bin")
			file.Name = "bin/kubectl"
			file.Checksum = map[string]string{
				"SHA256": "e5f7a7ed445673057c73686cb846e0c33ff0d5701fd43bf6aff16bb39ae14de2",
			}
			require.NoError(t, pkg.AddFile(file))

			tv, err := ldoc.Render()
			require.NoError(t, err)
			require.Contains(t, tv, "SPDXVersion: "+version+"\n")
			path := filepath.Join(t.TempDir(), "legacy.spdx")
			require.NoError(t, os.WriteFile(path, []byte(tv), 0o600))

			doc, err := OpenDoc(path)
			require.NoError(t, err)
			require.Equal(t, "legacy-doc", doc.Name)
			require.Len(t, doc.Packages, 1)
			for _, p := range doc.Packages {
				require.Equal(t, "kubectl", p.Name)
				require.Equal(t, "v1.33.0", p.Version)
				files := p.Files()
				require.Len(t, files, 1)
				require.Equal(t, "bin/kubectl", files[0].Name)
				require.Equal(t, file.Checksum["SHA256"], files[0].Checksum["SHA256"])
			}
		})
	}
}
