/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package spdx

import (
	"cmp"
	"errors"
	"fmt"
	"io"
	"slices"
	"strings"

	"github.com/protobom/protobom/pkg/formats"
	"github.com/protobom/protobom/pkg/sbom"
	"github.com/protobom/protobom/pkg/writer"
	"github.com/sirupsen/logrus"
	"google.golang.org/protobuf/proto"
)

// GenerateProtobom creates a new SBOM from the same options, and the
// same configuration file, as Generate, and returns it as a protobom
// document instead of converting it to the legacy model. The protobom
// document can be written in formats the legacy model does not know,
// like SPDX 3 with WriteSPDX3. Options only the legacy model carries
// are ignored with a warning.
//
// The document is generated by the engine directly rather than through
// the DocBuilderImplementation, whose GenerateDocument returns the
// legacy model: adding a protobom method to that interface would break
// its implementations outside of bom.
func (db *DocBuilder) GenerateProtobom(genopts *DocGenerateOptions) (*sbom.Document, error) {
	if err := db.impl.ReadYamlConfiguration(genopts.ConfigFile, genopts); err != nil {
		return nil, fmt.Errorf("parsing configuration file: %w", err)
	}

	if err := db.impl.ValidateOptions(genopts); err != nil {
		return nil, fmt.Errorf("checking build options: %w", err)
	}

	if len(genopts.ExternalDocumentRef) > 0 {
		logrus.Warnf(
			"External document references cannot be recorded in a protobom document, ignoring %d of them",
			len(genopts.ExternalDocumentRef),
		)
	}
	listVersion, err := licenseListVersion(genopts.LicenseListVersion)
	if err != nil {
		return nil, err
	}
	defaultVersion, err := licenseListVersion("")
	if err != nil {
		return nil, err
	}
	if listVersion != defaultVersion {
		logrus.Warnf(
			"The license list version cannot be recorded in a protobom document, ignoring %q",
			genopts.LicenseListVersion,
		)
	}

	return generateProtobom(genopts)
}

// WriteSPDX3 writes a protobom document to w as SPDX 3.0.1 JSON-LD,
// using protobom's serializer.
//
// The document is prepared first: its license data is normalized the
// same way FromProtobom normalizes it for SPDX 2.3 (every node states
// its declared licenses as a single valid license expression, and
// licenses that are NOASSERTION are left out, which is how SPDX 3 says
// nothing is asserted), external references without a URL are left out
// as in SPDX 2.3, and the graph is sorted, so the same document is
// written the same way every time. The document passed in is not
// modified.
func WriteSPDX3(w io.Writer, doc *sbom.Document) error {
	if doc == nil {
		return errors.New("document is nil")
	}
	if err := writer.New(writer.WithFormat(formats.SPDX3JSON)).WriteStream(prepareSPDX3(doc), w); err != nil {
		return fmt.Errorf("writing SPDX 3 document: %w", err)
	}
	return nil
}

// prepareSPDX3 returns a copy of the document prepared for protobom's
// SPDX 3 serializer.
//
// The serializer writes the elements, and numbers the license and
// relationship elements it mints, in the order of the node list, which
// the engine does not keep stable between runs: nodes, edges and root
// elements are sorted. protobom v0.6.2 writes hashes and identifiers
// deterministically (protobom/protobom#480), so the output is now
// byte-stable for a given document.
//
// External references without a URL, such as the VCS references unpack
// records for a codebase when it knows the commit but not the
// repository, are left out as the SPDX 2.3 output leaves them out:
// SPDX 3 would write them with an empty locator.
//
// The license data is normalized the same way FromProtobom normalizes
// it. The serializer joins the declared
// licenses of a node with AND without parenthesizing them, which turns
// a list like ["MIT OR Apache-2.0", "Zlib"] into an expression of a
// different meaning: each list is combined here into one expression,
// with the operator the SPDX 2.3 output uses, so there is nothing left
// to join.
func prepareSPDX3(doc *sbom.Document) *sbom.Document {
	doc = proto.Clone(doc).(*sbom.Document) //nolint:errcheck // Clone returns a copy of the type it is given
	sortNodeList(doc.GetNodeList())
	nodes := doc.GetNodeList().GetNodes()
	for _, node := range nodes {
		node.ExternalReferences = slices.DeleteFunc(node.GetExternalReferences(), func(ref *sbom.ExternalReference) bool {
			return ref.GetUrl() == ""
		})
	}
	refs := newLicenseRefs()
	refs.collecting = true
	for _, node := range nodes {
		nodeLicenses(node, refs)
	}
	refs.assign()
	for _, node := range nodes {
		concluded, declared := nodeLicenses(node, refs)
		node.LicenseConcluded = spdx3License(concluded)
		node.Licenses = nil
		if declared = spdx3License(declared); declared != "" {
			node.Licenses = []string{declared}
		}
	}
	return doc
}

// sortNodeList sorts the nodes of a node list by identifier, its edges
// by source, type and targets, the targets of each edge and its root
// elements, in place.
func sortNodeList(nl *sbom.NodeList) {
	slices.SortFunc(nl.GetNodes(), func(a, b *sbom.Node) int {
		return strings.Compare(a.GetId(), b.GetId())
	})
	for _, edge := range nl.GetEdges() {
		slices.Sort(edge.GetTo())
	}
	slices.SortStableFunc(nl.GetEdges(), func(a, b *sbom.Edge) int {
		return cmp.Or(
			strings.Compare(a.GetFrom(), b.GetFrom()),
			cmp.Compare(a.GetType(), b.GetType()),
			slices.Compare(a.GetTo(), b.GetTo()),
		)
	})
	slices.Sort(nl.GetRootElements())
}

// spdx3License returns the license expression to write in SPDX 3, which
// says nothing is asserted by leaving the license out.
func spdx3License(expr string) string {
	if expr == NOASSERTION {
		return ""
	}
	return expr
}
