name: Validate SPDX Conformance

on:
  pull_request:
    branches:
      - 'main'

permissions: {}

jobs:
  check-spdx:
    name: Check SPDX SBOMs
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Extract version of Go to use
        run: echo "GOVERSION=$(awk -F'[:@]' '/FROM golang/{print $2; exit}' Dockerfile.dev)" >> $GITHUB_ENV

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: '${{ env.GOVERSION }}'
          check-latest: true
          cache: false

      - run: |
          go run ./cmd/bom/main.go generate --format=json -i registry.k8s.io/pause > example-image-pause.spdx.json

      - uses: chainguard-dev/actions/setup-spdx@a9d4aa7202a63f8a6b8f81bb1570a0ca54460ac5 # v1.6.34
        with:
          spdx-tools-version: 2.0.7

      - uses: chainguard-dev/actions/setup-spdx@a9d4aa7202a63f8a6b8f81bb1570a0ca54460ac5 # v1.6.34
        with:
          download: false
          spdx-tools-version: 2.0.7
          sbom-path: example-image-pause.spdx.json
          sbom-format: JSON

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        if: ${{ always() }}
        with:
          name: Example SBOMs
          path: |
            example-image-pause.spdx.json
